FROM postgres:11.2
MAINTAINER Francine Youndzo <francine.youndzokengne@heig-vd.ch>

volumes:
-/Users/youndzofrancine/Desktop/Projet_de_semestre/script_db:/docker-entrypoint-initdb.d/

ADD data/ /Users/youndzofrancine/Desktop/Projet_de_semestre/script_db:/docker-entrypoint-initdb.d/

